[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[override]]
  # only needed until kubernetes moves to dep or github.com/docker/distribution's latest tag builds with kubernetes.
  name = "github.com/docker/distribution"
  #revision = "master"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/sacloud/libsacloud"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.1"

[[override]]
  name = "github.com/vmware/photon-controller-go-sdk"
  revision = "4a435daef6ccd3d0edaac1161e76f51a70c2589a"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "781450b3c4fcb4f5182bcc5133adb4b2e4a09d1d"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "da91af54816b4cf72949c225a2d0980f51fab01b"
