[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[override]]
  # only needed until kubernetes moves to dep or github.com/docker/distribution's latest tag builds with kubernetes.
  name = "github.com/docker/distribution"
  #revision = "master"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/sacloud/libsacloud"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.12.3"
